---
# tasks file for gcm


- name: Add git apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa
    state: present
    update_cache: true

- name: Get git package
  become: true
  ansible.builtin.apt:
    name: git
    state: present
  when: ansible_os_family == 'Debian'

- name: Get packages needed
  become: true
  ansible.builtin.apt:
    name: "{{ gcm_apt_packages }}"
    state: present
    update_cache: "{{ gcm_update_apt_cache_for_dot_net }}"
  when: ansible_os_family == 'Debian'

# https://learn.microsoft.com/en-us/dotnet/core/install/linux-package-mixup?pivots=os-linux-ubuntu#solutions
- name: Get package source
  ansible.builtin.set_fact:
    package_source:
      "{{ lookup('pipe', 'apt-cache policy ''~ndotnet.*'' | grep -v microsoft | grep ''/ubuntu'' | grep updates | cut -d\"/\" -f3 | sort -u') }}"  # noqa: jinja[spacing] yaml[line-length]

- name: Make sure to not use the default package store
  become: true
  ansible.builtin.blockinfile:
    path: /etc/apt/preferences
    create: true
    mode: '0644'
    block: |
      Package: dotnet* aspnet* netstandard*
      Pin: origin "{{ package_source }}"
      Pin-Priority: -10

- name: Import Microsoft signing key for apt
  become: true
  retries: 3
  delay: 5
  ansible.builtin.apt_key:
    url: "{{ gcm_repo_key_url }}"
    state: present

- name: Check if dot net is installed from other package store
  ansible.builtin.set_fact:
    dot_net_remove: "{{ lookup('pipe', 'dotnet --list-sdks | grep /usr/lib', errors='ignore') }}"
  changed_when: dot_net_remove != ""

- name: Remove existing dotnet versions
  become: true
  ansible.builtin.apt:
    name: "{{ gcm_dot_net_package_removes }}"
    state: absent
  when: dot_net_remove != ""

- name: Check if dot net sdk is installed
  ansible.builtin.set_fact:
    dot_net: "{{ lookup('pipe', 'dotnet --list-sdks | grep 7.0', errors='ignore') }}"
  changed_when: dot_net == ""

- name: Install dot net sdk
  become: true
  ansible.builtin.apt:
    name: "{{ gcm_dot_net_package_name }}"
  when: dot_net == ""

- name: Check if git credential manager is installed
  ansible.builtin.set_fact:
    gcm_tool: "{{ lookup('pipe', 'dotnet tool list -g | grep git-credential-manager', errors='ignore') }}"
  changed_when: gcm_tool == ""

- name: Install GCM
  ansible.builtin.command: dotnet tool install -g git-credential-manager
  when: gcm_tool == ""
  changed_when: gcm_tool == ""

- name: Set GCM Configuration for gpg
  community.general.git_config:
    name: "credential.credentialStore"
    scope: global
    value: gpg

- name: Set GCM Configuration for Azure DevOps
  community.general.git_config:
    name: "credential.azreposCredentialType"
    scope: global
    value: oauth

- name: Get repo tool
  become: true
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/git-repo-downloads/repo
    mode: "0775"
    dest: /bin/repo

- name: Configure .bashrc to include ~/.local/bin
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    block: |
      if [[ ":${PATH}:" != *":${HOME}/.local/bin:"* ]]; then
          PATH="${HOME}/.local/bin:${PATH}"
      fi
