---
# tasks file for gcm


- name: Add git apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa
    state: present
    update_cache: true

- name: Get git package
  become: true
  ansible.builtin.apt:
    name: git
    state: present
  when: ansible_os_family == 'Debian'

- name: Get packages needed for dot net install
  become: true
  ansible.builtin.apt:
    name: "{{ gcm_apt_packages }}"
    state: present
    update_cache: "{{ gcm_update_apt_cache_for_dot_net }}"
  when: ansible_os_family == 'Debian'

# https://learn.microsoft.com/en-us/dotnet/core/install/linux-package-mixup?pivots=os-linux-ubuntu#solutions
- name: Get package source
  ansible.builtin.set_fact:
    package_source:
      "{{ lookup('pipe', 'apt-cache policy ''~ndotnet.*'' | grep -v microsoft | grep ''/ubuntu'' | grep updates | cut -d\"/\" -f3 | sort -u') }}"  # noqa: jinja[spacing] yaml[line-length]

- name: Make sure to not use the default package store
  become: true
  ansible.builtin.blockinfile:
    path: /etc/apt/preferences
    create: true
    mode: '0644'
    block: |
      Package: dotnet* aspnet* netstandard*
      Pin: origin "{{ package_source }}"
      Pin-Priority: -10

- name: Import Microsoft signing key for apt
  become: true
  retries: 3
  delay: 5
  ansible.builtin.apt_key:
    url: "{{ gcm_repo_key_url }}"
    state: present

- name: Install dot net
  become: true
  ansible.builtin.apt:
    name: "{{ gcm_dot_net_package_name }}"

- name: Check if git credential manager is installed
  ansible.builtin.set_fact:
    gcm_tool: "{{ lookup('pipe', 'dotnet tool list -g | grep git-credential-manager', errors='ignore') }}"
  changed_when: gcm_tool == ""

- name: Install GCM
  ansible.builtin.command: dotnet tool install -g git-credential-manager
  when: gcm_tool == ""
  changed_when: gcm_tool == ""

- name: Create command to start dbus
  ansible.builtin.template:
    src: ../files/startdbus
    dest: ~/.local/bin/startdbus
    mode: '0755'

- name: Create command to unlock keyring
  ansible.builtin.template:
    src: ../files/unlock
    dest: ~/.local/bin/unlock
    mode: '0755'

- name: Set GCM Configuration for Azure DevOps
  community.general.git_config:
    name: "credential.azreposCredentialType"
    scope: global
    value: oauth

- name: Configure .bashrc to include ~/.local/bin
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    block: |
      if [[ ":${PATH}:" != *":${HOME}/.local/bin:"* ]]; then
          PATH="${HOME}/.local/bin:${PATH}"
      fi

- name: Source .bashrc
  ansible.builtin.shell: source ~/.bashrc
  args:
    executable: /usr/bin/bash
  changed_when: false